### ISSUE TITLE
OTA download link not working

### ISSUE THREAD

**Issue by chromer030** [mg712702/device_ota#1]
Hi , Thank you for keeping this device alive...
OTA download link not working :

[https://doc-04-64-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/9alvet5l2okc2a55grinbtjhv19oq3a0/1578556800000/02243883509275055055/*/1EBTKGDzJWXGE1I4tdebdMdP4a1tTRoAv?e=download](url)

**Comment by mg712702** [comment]
This is just for testing purposes, not for public release..
